name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Get today's date
        run: echo "DATE_TAG=$(date +'%d%m%y')" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t almaleeh/adhancast:${{ env.DATE_TAG }} .

      - name: Push Docker Image to Docker Hub
        run: docker push almaleeh/adhancast:${{ env.DATE_TAG }}
